### YamlMime:UniversalReference
items:
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode:enum'
    summary: |-
      自定义函数的错误代码。 错误代码将显示在调用函数的单元格中。

      除了这些错误代码之外，还将显示自定义错误消息。 自定义邮件显示在错误指示器菜单中，该菜单通过将鼠标悬停在包含错误的每个单元格上的错误标志上方来访问。
    name: CustomFunctions.ErrorCode
    fullName: CustomFunctions.ErrorCode
    langs:
      - typeScript
    type: enum
    package: custom-functions-runtime!
    children:
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member'
    summary: '此错误代码指示使用的函数被零或空单元格除。 无法使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: divisionByZero
    fullName: divisionByZero
    langs:
      - typeScript
    type: field
    numericValue: '"#DIV/0!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member'
    summary: '此错误代码指示函数名称中有拼写错误。 请注意，此错误代码支持为自定义函数输入错误，而不是作为自定义函数输出错误。 无法使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidName
    fullName: invalidName
    langs:
      - typeScript
    type: field
    numericValue: '"#NAME?"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member'
    summary: '此错误代码指示函数中的某个数字存在问题。 无法使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidNumber
    fullName: invalidNumber
    langs:
      - typeScript
    type: field
    numericValue: '"#NUM!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member'
    summary: '此错误代码指示函数引用了无效的单元格。 请注意，此错误代码支持为自定义函数输入错误，而不是作为自定义函数输出错误。 无法使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidReference
    fullName: invalidReference
    langs:
      - typeScript
    type: field
    numericValue: '"#REF!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member'
    summary: '此错误代码指示函数中的值的数据类型错误。 如果需要，除了错误代码之外，还可以使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidValue
    fullName: invalidValue
    langs:
      - typeScript
    type: field
    numericValue: '"#VALUE!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member'
    summary: '此错误代码指示函数或服务不可用。 如果需要，除了错误代码之外，还可以使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: notAvailable
    fullName: notAvailable
    langs:
      - typeScript
    type: field
    numericValue: '"#N/A"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member'
    summary: '此错误代码指示函数中的区域不相交。 无法使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: nullReference
    fullName: nullReference
    langs:
      - typeScript
    type: field
    numericValue: '"#NULL!"'